#define UMIN(a, b)				((a) < (b) ? (a) : (b))
#define UMAX(a, b)				((a) > (b) ? (a) : (b))
#define URANGE(a, b, c)			((b) < (a) ? (a) : ((b) > (c) ? (c) : (b)))
#define IS_SET(flag, bit)		((flag) & (bit))
#define SET_BIT(var, bit)		((var) |= (bit))
#define REMOVE_BIT(var, bit)	((var) &= ~(bit))
#define LOWER(c)				((c) >= 'A' && (c) <= 'Z' ? (c)+'a'-'A' : (c))
#define UPPER(c)				((c) >= 'a' && (c) <= 'z' ? (c)+'A'-'a' : (c))

#define MB(str)					(MessageBox(NULL, (str), (str), NULL))
